[files]
extend-exclude = []
ignore-hidden = true
ignore-files = true
ignore-dot = true
ignore-vcs = true
ignore-global = true
ignore-parent = true

[default]
binary = false
check-filename = true
check-file = true
unicode = true
ignore-hex = true
identifier-leading-digits = false
locale = "en"
extend-ignore-identifiers-re = []
extend-ignore-words-re = ["OT","VAS","DAA","OpenVAS","THR", "RTO", "SIE", "BA","NDAs", "SHS", "Pn"]
extend-ignore-re = ["(?Rm)^.*//\\s*spellchecker:disable-line$"]